/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import entity.*;
import dao.*;

import utils.*;
import javax.swing.JPanel;

/**
 *
 * @author Tien
 */
public class AdminUI extends javax.swing.JFrame {

    DocGiaDAO dgDAO = new DocGiaDAO();

    /**
     * Creates new form Main
     */
    public AdminUI() {
        initComponents();
        init();
        System.out.println(AccountDAO.getCurrentId());
    }

    private void changeTabs(JPanel p) {
        pnlHienThi.removeAll();
        pnlHienThi.add(p);
        pnlHienThi.repaint();
        pnlHienThi.revalidate();

    }

    private void init() {
        this.setLocationRelativeTo(null);
        DocGia dg = dgDAO.selectById(AccountDAO.getCurrentId());
        System.out.println(dg);
        lblId.setText(dg.getDocGiaId() + "");
        lblTen.setText(dg.getHoten() + "");

        QLSach qls = new QLSach();
        changeTabs(qls);
        TaskManager.getInstance().submitTask(() -> {
            qls.loadTableSach();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jpanelGradient1 = new utils.JpanelGradient();
        jLabel2 = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        lblShowID = new javax.swing.JLabel();
        btnSach = new javax.swing.JButton();
        btnDocGia = new javax.swing.JButton();
        btnDanhMuc = new javax.swing.JButton();
        btnViPham = new javax.swing.JButton();
        btnMuonTra = new javax.swing.JButton();
        btnDoiMatKhau = new javax.swing.JButton();
        btnDangXua = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        pnlHienThi = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(234, 239, 239));

        jpanelGradient1.setColorEnd(new java.awt.Color(148, 129, 203));
        jpanelGradient1.setColorStart(new java.awt.Color(194, 227, 241));
        jpanelGradient1.setPreferredSize(new java.awt.Dimension(256, 720));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/avatar-small.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        lblTen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTen.setText("Tên người dùng");

        lblShowID.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblShowID.setText("ID:");

        btnSach.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sach.png"))); // NOI18N
        btnSach.setText("Quản lý sách");
        btnSach.setContentAreaFilled(false);
        btnSach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSach.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSach.setIconTextGap(10);
        btnSach.setMargin(new java.awt.Insets(0, 14, 3, 14));
        btnSach.setPreferredSize(new java.awt.Dimension(0, 38));
        btnSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSachMouseClicked(evt);
            }
        });

        btnDocGia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnDocGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        btnDocGia.setText("Quản lý  độc giả");
        btnDocGia.setContentAreaFilled(false);
        btnDocGia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDocGia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDocGia.setIconTextGap(10);
        btnDocGia.setMargin(new java.awt.Insets(0, 14, 3, 14));
        btnDocGia.setPreferredSize(new java.awt.Dimension(0, 38));
        btnDocGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDocGiaMouseClicked(evt);
            }
        });
        btnDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocGiaActionPerformed(evt);
            }
        });

        btnDanhMuc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnDanhMuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/danhmuc.png"))); // NOI18N
        btnDanhMuc.setText("  Quản lý danh mục");
        btnDanhMuc.setContentAreaFilled(false);
        btnDanhMuc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDanhMuc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDanhMuc.setIconTextGap(20);
        btnDanhMuc.setMargin(new java.awt.Insets(0, 14, 3, 14));
        btnDanhMuc.setPreferredSize(new java.awt.Dimension(0, 38));
        btnDanhMuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDanhMucMouseClicked(evt);
            }
        });
        btnDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhMucActionPerformed(evt);
            }
        });

        btnViPham.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnViPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vipham.png"))); // NOI18N
        btnViPham.setText("   Quản lý vi phạm");
        btnViPham.setContentAreaFilled(false);
        btnViPham.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViPham.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnViPham.setIconTextGap(10);
        btnViPham.setMargin(new java.awt.Insets(0, 14, 3, 14));
        btnViPham.setPreferredSize(new java.awt.Dimension(0, 38));
        btnViPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViPhamMouseClicked(evt);
            }
        });

        btnMuonTra.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnMuonTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/muontra.png"))); // NOI18N
        btnMuonTra.setText("Quản lý mượn trả");
        btnMuonTra.setContentAreaFilled(false);
        btnMuonTra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMuonTra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMuonTra.setIconTextGap(10);
        btnMuonTra.setMargin(new java.awt.Insets(0, 14, 3, 14));
        btnMuonTra.setPreferredSize(new java.awt.Dimension(0, 38));
        btnMuonTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMuonTraMouseClicked(evt);
            }
        });

        btnDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/doimatkhau.png"))); // NOI18N
        btnDoiMatKhau.setText("Đổi mật khẩu");
        btnDoiMatKhau.setContentAreaFilled(false);
        btnDoiMatKhau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDoiMatKhau.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDoiMatKhau.setIconTextGap(10);
        btnDoiMatKhau.setMargin(new java.awt.Insets(0, 14, 3, 14));
        btnDoiMatKhau.setPreferredSize(new java.awt.Dimension(0, 38));
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });

        btnDangXua.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnDangXua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dangxuat.png"))); // NOI18N
        btnDangXua.setText("Đăng xuất");
        btnDangXua.setContentAreaFilled(false);
        btnDangXua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangXua.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDangXua.setIconTextGap(10);
        btnDangXua.setMargin(new java.awt.Insets(0, 14, 3, 14));
        btnDangXua.setPreferredSize(new java.awt.Dimension(0, 38));
        btnDangXua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("__________________________________________");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("__________________________________________");

        lblId.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblId.setText("ID");

        javax.swing.GroupLayout jpanelGradient1Layout = new javax.swing.GroupLayout(jpanelGradient1);
        jpanelGradient1.setLayout(jpanelGradient1Layout);
        jpanelGradient1Layout.setHorizontalGroup(
            jpanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelGradient1Layout.createSequentialGroup()
                .addGroup(jpanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDoiMatKhau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDangXua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpanelGradient1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDocGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMuonTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpanelGradient1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jpanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnViPham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDanhMuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jpanelGradient1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jpanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpanelGradient1Layout.createSequentialGroup()
                                        .addComponent(lblShowID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblTen))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelGradient1Layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addGroup(jpanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jpanelGradient1Layout.setVerticalGroup(
            jpanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelGradient1Layout.createSequentialGroup()
                .addGroup(jpanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelGradient1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jpanelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblShowID)
                            .addComponent(lblId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTen))
                    .addGroup(jpanelGradient1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)))
                .addGap(56, 56, 56)
                .addComponent(jLabel4)
                .addGap(45, 45, 45)
                .addComponent(btnSach, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnMuonTra, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViPham, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addComponent(btnDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnDangXua, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlHienThi.setBackground(new java.awt.Color(234, 239, 239));
        pnlHienThi.setPreferredSize(new java.awt.Dimension(1024, 720));
        pnlHienThi.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jpanelGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHienThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpanelGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDocGiaActionPerformed

    private void btnDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhMucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDanhMucActionPerformed

    private void btnSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSachMouseClicked
        QLSach qls = new QLSach();
        changeTabs(qls);
        TaskManager.getInstance().submitTask(() -> {
            qls.loadTableSach();
        });


    }//GEN-LAST:event_btnSachMouseClicked

    private void btnDanhMucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDanhMucMouseClicked

        changeTabs(new QLDanhMuc());


    }//GEN-LAST:event_btnDanhMucMouseClicked

    private void btnDocGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDocGiaMouseClicked
        changeTabs(new QLDocGia());


    }//GEN-LAST:event_btnDocGiaMouseClicked

    private void btnMuonTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMuonTraMouseClicked
        QLMuonTra qlmt = new QLMuonTra();
        changeTabs(qlmt);
        TaskManager.getInstance().submitTask(() -> {
            qlmt.loadPhieuMuon();

        });
        TaskManager.getInstance().submitTask(() -> {
            qlmt.loadTableSach();

        });


    }//GEN-LAST:event_btnMuonTraMouseClicked

    private void btnViPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViPhamMouseClicked

        changeTabs(new QLViPham());


    }//GEN-LAST:event_btnViPhamMouseClicked

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        new DoiMatKhau().setVisible(true);
    }//GEN-LAST:event_btnDoiMatKhauActionPerformed

    private void btnDangXuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuaActionPerformed
        this.dispose();
        new DangNhap().setVisible(true);
    }//GEN-LAST:event_btnDangXuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXua;
    private javax.swing.JButton btnDanhMuc;
    private javax.swing.JButton btnDocGia;
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnMuonTra;
    private javax.swing.JButton btnSach;
    private javax.swing.JButton btnViPham;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private utils.JpanelGradient jpanelGradient1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblShowID;
    private javax.swing.JLabel lblTen;
    private javax.swing.JPanel pnlHienThi;
    // End of variables declaration//GEN-END:variables
}
