/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import dao.*;
import entity.*;
import utils.XDialog;
import utils.XValidate;
import java.util.Properties;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.Timer;

/**
 *
 * @author Tien
 */
public class QuenMatKhau extends javax.swing.JFrame {

    AccountDAO acDAO = new AccountDAO();
    String maCode = "";

    /**
     * Creates new form QuenMatKhau
     */
    public QuenMatKhau() {
        initComponents();
        init();
    }

    private void init() {
        this.setLocationRelativeTo(null);
    }

    private void recoveryPass() {
        Account ac = acDAO.selectByEmail(txtEmail.getText());
        if (XValidate.checkNullText(txtEmail)
                && XValidate.checkNullText(pwdPass)
                && XValidate.checkNullText(txtMaXacThuc)) {
            if (txtMaXacThuc.getText().equals(maCode)) {
                ac.setPass(new String(pwdPass.getPassword()));
                acDAO.update(ac);
                XDialog.alert(this, "Khôi phục mật khẩu thành công");
                clearForm();
            } else {
                XDialog.alert(this, "Mã xác thực không đúng");
            }

        }

    }

    private String randomCode() {
        int number1 = (int) Math.ceil(Math.random() * 9);
        int number2 = (int) Math.ceil(Math.random() * 9);
        int number3 = (int) Math.ceil(Math.random() * 9);
        int number4 = (int) Math.ceil(Math.random() * 9);
        int number5 = (int) Math.ceil(Math.random() * 9);
        int number6 = (int) Math.ceil(Math.random() * 9);
        return "" + number1 + number2 + number3 + number4 + number5 + number6;
    }

    private void clearForm() {
        txtEmail.setText("");
        txtMaXacThuc.setText("");
        pwdPass.setText("");
    }

    private void sendMail(String to) {
        // Thông tin cấu hình cho kết nối SMTP
        String host = "smtp.gmail.com";
        final String user = "tienvtps40685@gmail.com"; // Thay thế bằng email của bạn
        final String password = "raft uzed uukz ltvo"; // Thay thế bằng mật khẩu của bạn

        // Thiết lập các thuộc tính SMTP
        Properties properties = new Properties();
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.host", host);
        properties.put("mail.smtp.port", "587");

        // Tạo một phiên làm việc với thông tin xác thực
        Session session = Session.getInstance(properties, new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(user, password);
            }
        });

        try {

            // Tạo một tin nhắn email
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(user));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));
            message.setSubject("TẠO LẠI MẬT KHẨU CHO ỨNG DỤNG THƯ VIỆN");
            message.setText("Mã xác nhận của bạn là:" + maCode);

            // Gửi tin nhắn
            Transport.send(message);

        } catch (MessagingException e) {
            e.printStackTrace();
            System.out.println("Gửi email thất bại");
        }
    }

    private void startCountdown() {
        int[] seconds = {30}; // Biến seconds là một mảng
        new Timer(1000, e -> {
            if (seconds[0] > 0) {
                seconds[0]--;
                lblLayMa.setText(seconds[0] + "");
                lblLayMa.setEnabled(false);
            } else {
                ((Timer) e.getSource()).stop();
                lblLayMa.setText("Lấy mã");
                lblLayMa.setEnabled(true);
            }
        }).start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblLayMa = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnKhoiPhuc = new javax.swing.JButton();
        lblSignIn = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        pwdPass = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        txtMaXacThuc = new javax.swing.JTextField();
        lblsShow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bgc_sach.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(251, 234, 234));

        lblLayMa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblLayMa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLayMa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reload.png"))); // NOI18N
        lblLayMa.setText("Lấy mã");
        lblLayMa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLayMa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLayMaMouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/avatar.png"))); // NOI18N
        jLabel7.setText("jLabel2");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Email");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Mật khẩu mới:");

        btnKhoiPhuc.setBackground(new java.awt.Color(110, 116, 255));
        btnKhoiPhuc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnKhoiPhuc.setForeground(new java.awt.Color(255, 255, 255));
        btnKhoiPhuc.setText("Khôi phục");
        btnKhoiPhuc.setBorderPainted(false);
        btnKhoiPhuc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKhoiPhuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoiPhucActionPerformed(evt);
            }
        });

        lblSignIn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSignIn.setText("Đăng nhập");
        lblSignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSignInMouseClicked(evt);
            }
        });

        txtEmail.setToolTipText("Email");

        pwdPass.setToolTipText("Mật khẩu");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Nhập mã xác thực");

        txtMaXacThuc.setToolTipText("Mã xác thực");

        lblsShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/show.png"))); // NOI18N
        lblsShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblsShowMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblsShowMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKhoiPhuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pwdPass, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                    .addComponent(txtEmail))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblsShow))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtMaXacThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblLayMa)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(lblSignIn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addGap(33, 33, 33)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblsShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwdPass, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLayMa)
                    .addComponent(txtMaXacThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKhoiPhuc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSignIn)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKhoiPhucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoiPhucActionPerformed
        recoveryPass();
    }//GEN-LAST:event_btnKhoiPhucActionPerformed

    private void lblSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignInMouseClicked
        this.dispose();
        new DangNhap().setVisible(true);
    }//GEN-LAST:event_lblSignInMouseClicked

    private void lblLayMaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLayMaMouseClicked

        Account ac = acDAO.selectByEmail(txtEmail.getText());
        if (XValidate.checkNullText(txtEmail)
                && XValidate.checkNullText(pwdPass)) {
            if (ac == null) {
                XDialog.alert(this, "Không tìm thấy tài khoản");
            } else {
                maCode = randomCode();
                startCountdown();

                //Đưa việc gửi mail vào luồng phụ
                ExecutorService executor = Executors.newSingleThreadExecutor();
                executor.submit(() -> {
                    sendMail(txtEmail.getText());
                });
                executor.shutdown();
            }

        }


    }//GEN-LAST:event_lblLayMaMouseClicked

    private void lblsShowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsShowMousePressed
        pwdPass.setEchoChar((char) 0);
    }//GEN-LAST:event_lblsShowMousePressed

    private void lblsShowMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsShowMouseReleased
        pwdPass.setEchoChar('*');
    }//GEN-LAST:event_lblsShowMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuenMatKhau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKhoiPhuc;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblLayMa;
    private javax.swing.JLabel lblSignIn;
    private javax.swing.JLabel lblsShow;
    private javax.swing.JPasswordField pwdPass;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaXacThuc;
    // End of variables declaration//GEN-END:variables
}
